### ISSUE TITLE
无法找到歌曲

### ISSUE THREAD

**Issue by Ilovexiu** [nICEnnnnnnnLee/MiraMira#3]
2024-03-09 11:44:11 V/Bot.2978928081: [起个什么名字好呢(571520977)] 不到150斤不改昵称(2278928081) -> 网易云 Keep you mine
2024-03-09 11:44:11 W/stderr: org.json.JSONException: JSONObject["result"] not found.
2024-03-09 11:44:11 W/stderr:   at miramira-v0.1.2.mirai2.jar//org.json.JSONObject.get(JSONObject.java:587)
2024-03-09 11:44:11 W/stderr:   at miramira-v0.1.2.mirai2.jar//org.json.JSONObject.getJSONObject(JSONObject.java:797)
2024-03-09 11:44:11 W/stderr:   at miramira-v0.1.2.mirai2.jar//top.nicelee.mirai.miramira.app.music.libs.NetEaseMusic.searchWithoutLink(NetEaseMusic.java:55)
2024-03-09 11:44:11 W/stderr:   at miramira-v0.1.2.mirai2.jar//top.nicelee.mirai.miramira.app.music.MusicGMsgHandler.accept(MusicGMsgHandler.java:45)
2024-03-09 11:44:11 W/stderr:   at miramira-v0.1.2.mirai2.jar//top.nicelee.mirai.miramira.app.music.MusicGMsgHandler.accept(MusicGMsgHandler.java:18)
2024-03-09 11:44:11 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605)
2024-03-09 11:44:11 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605)
2024-03-09 11:44:11 W/stderr:   at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
2024-03-09 11:44:11 W/stderr:   at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
2024-03-09 11:44:11 W/stderr:   at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
2024-03-09 11:44:11 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-03-09 11:44:11 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-03-09 11:44:11 W/stderr:   at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2024-03-09 11:44:11 W/stderr:   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2024-03-09 11:44:11 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-03-09 11:44:11 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-03-09 11:44:11 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-03-09 11:44:11 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-03-09 11:44:12 V/Bot.2978928081: Group(571520977) <- 已为你找到以下歌曲：
发送序号即可点歌
>
---------------------------------------------------------------------------------------------------------------------------------
好像缺了个json，求助大佬

**Comment by nICEnnnnnnnLee** [comment]
现在详细搜索的接口需要登录，用另一个接口只能出来四条近似的结果，而在这几条结果里还很有可能需要会员所以无法播放。比较鸡肋
